// WebMCP tools: lets an AI agent in the browser ask this page for facts and actions directly instead of
// scraping it (https://developer.chrome.com/docs/ai/webmcp). Only registered where the browser offers
// `modelContext`; everywhere else this file does nothing. All data comes from the same places the page
// uses — latest.json and changelog.md on this origin — so tools and page can never disagree.
(function () {
  'use strict';

  var mc = (typeof document !== 'undefined' && document.modelContext) ||
    (typeof navigator !== 'undefined' && navigator.modelContext);
  if (!mc || typeof mc.registerTool !== 'function') return;

  // Facts from site.json (generated by build.py).
  var FACTS = {
    "name": "Loupe",
    "summary": "Loupe is a free, open-source Quick Look extension for macOS 14+. Press Space on a file in Finder and it shows JSON as a collapsible tree with exact error positions, renders Markdown, turns log files into a colour-coded table (newest lines first in view), lays out TSV as a table and highlights source code in 20+ languages, PowerShell, Batch and XML dialects included. It runs sandboxed, read-only and offline, and its previews contain no JavaScript. A companion app switches previews on or off per category and sets appearance, text size and language (English or German).",
    "requirements": {
      "macos": "macOS 14+ · Apple silicon"
    },
    "platforms": [
      "JSON",
      "Markdown",
      "Logs",
      "TSV",
      "XML",
      "PowerShell",
      "Batch",
      "Swift",
      "Python",
      "Rust",
      "Go",
      "YAML"
    ],
    "features": [
      "Collapsible JSON tree with exact line and column of syntax errors",
      "Markdown rendering (GitHub flavoured) with blocked remote images",
      "Log files as a table: time, level, source, message; seven formats; big logs read from the end",
      "TSV files as a table with numeric columns aligned",
      "Syntax highlighting for 20+ languages including PowerShell, Batch and XML dialects",
      "Switch previews on or off, globally or per category",
      "Light and dark appearance, three text sizes; companion app in English and German",
      "Sandboxed, read-only, offline; previews contain no JavaScript"
    ],
    "limits": [
      "macOS 14 or later on Apple silicon only",
      "CSV (.csv) cannot be previewed: macOS reserves that type for its own generator — use .tsv",
      "Some file types (.ts, .tsx, .jsx, .scss …) never reach Quick Look extensions because macOS types them differently",
      "Not notarized: ad-hoc signed, so the first launch needs right-click → Open",
      "Read-only: Loupe shows files, it does not edit them"
    ],
    "targets": [
      "macos"
    ],
    "signing": [],
    "links": {
      "page": "https://loupe.celox.io/",
      "download": "https://loupe.celox.io/download",
      "latest": "https://loupe.celox.io/latest.json",
      "markdown": "https://loupe.celox.io/index.md",
      "changelog": "https://loupe.celox.io/changelog.md",
      "skill": "https://loupe.celox.io/skills/get-loupe/SKILL.md",
      "source": "https://github.com/pepperonas/loupe",
      "licence": "https://github.com/pepperonas/loupe/blob/main/LICENSE"
    }
  };
  var SITE = FACTS.links.page.replace(/\/$/, '');
  var LANGS = ["en", "de"];

  function latest(signal) {
    return fetch('/latest.json', { cache: 'no-cache', signal: signal }).then(function (r) {
      if (!r.ok) throw new Error('latest.json: HTTP ' + r.status);
      return r.json();
    });
  }
  function json(v) { return JSON.stringify(v, null, 2); }
  var READ = { readOnlyHint: true };

  var tools = [
    {
      name: 'get_app_facts',
      description: 'What Loupe is: a one-paragraph summary, requirements, supported platforms, ' +
        'features, limits and the important links (download, source, changelog, licence).',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
      annotations: READ,
      execute: function () { return Promise.resolve(json(FACTS)); }
    },
    {
      name: 'get_latest_release',
      description: 'The newest release of Loupe: version, publication date, release notes URL ' +
        'and every file with its download URL, size in bytes and SHA-256.',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
      annotations: READ,
      execute: function (_input, opts) {
        return latest(opts && opts.signal).then(function (d) {
          return json({ version: d.version, published: d.published, notes: d.notes, assets: d.assets ||
            [{ target: FACTS.targets[0], name: d.name, url: d.url, size: d.size, sha256: d.sha256 }] });
        });
      }
    },
    {
      name: 'get_download_url',
      description: 'The direct download URL of the newest Loupe file for a platform (macos), plus ' +
        'the stable link that always redirects to the newest file.',
      inputSchema: {
        type: 'object',
        properties: { platform: { type: 'string', enum: FACTS.targets, description: 'Target platform; default: ' + FACTS.targets[0] + '.' } },
        additionalProperties: false
      },
      annotations: READ,
      execute: function (input, opts) {
        return latest(opts && opts.signal).then(function (d) {
          var assets = d.assets || [{ target: FACTS.targets[0], name: d.name, url: d.url, size: d.size }];
          var want = (input && input.platform) || assets[0].target;
          var a = assets.filter(function (x) { return x.target === want; })[0] || assets[0];
          return json({ version: d.version, platform: a.target, file: a.name, url: a.url, size: a.size,
            stable_link: SITE + '/download/' + a.target });
        });
      }
    },
    {
      name: 'get_checksums',
      description: 'How to verify a downloaded Loupe file: the SHA-256 of every file of the newest release ' +
        'and the fixed signing facts.',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
      annotations: READ,
      execute: function (_input, opts) {
        return latest(opts && opts.signal).then(function (d) {
          var assets = d.assets || [{ name: d.name, sha256: d.sha256 }];
          return json({ version: d.version,
            files: assets.map(function (a) { return { name: a.name, sha256: a.sha256 }; }),
            signing: FACTS.signing });
        });
      }
    },
    {
      name: 'get_changelog',
      description: 'The most recent entries of the Loupe changelog as Markdown.',
      inputSchema: {
        type: 'object',
        properties: { versions: { type: 'integer', minimum: 1, maximum: 10, description: 'How many versions (default 3).' } },
        additionalProperties: false
      },
      annotations: READ,
      execute: function (input, opts) {
        var n = Math.min(10, Math.max(1, (input && input.versions) || 3));
        return fetch('/changelog.md', { cache: 'no-cache', signal: opts && opts.signal }).then(function (r) {
          if (!r.ok) throw new Error('changelog.md: HTTP ' + r.status);
          return r.text();
        }).then(function (md) {
          var parts = md.split(/\n(?=## \[)/).slice(1).filter(function (s) { return !/^## \[Unreleased\]\s*$/.test(s.trim()); });
          return parts.slice(0, n).join('\n').trim();
        });
      }
    },
    {
      name: 'set_page_language',
      description: 'Show this page in another language (English, German, Spanish, Italian or French).',
      inputSchema: {
        type: 'object',
        properties: { language: { type: 'string', enum: LANGS, description: 'ISO 639-1 code.' } },
        required: ['language'],
        additionalProperties: false
      },
      annotations: { readOnlyHint: false },
      execute: function (input) {
        if (LANGS.indexOf(input.language) < 0) throw new Error('unsupported language: ' + input.language);
        if (typeof window.SITE_setLanguage === 'function') window.SITE_setLanguage(input.language);
        return Promise.resolve('Page language set to ' + input.language + '.');
      }
    }
  ];

  tools.forEach(function (t) {
    try { mc.registerTool(t); } catch (e) { /* a browser with an older WebMCP shape: skip that tool */ }
  });
})();
